version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: ["python", "app.py"]
  hack:
    build: .
    volumes:
      - .:/app
    command: ["python", "hack.py"]
    links:
      - web
